[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/cplessis/ASVmaker"
"Bug Tracker" = "https://github.com/cplessis/ASVmaker/issues"